version: '3.8'

services:
  claude-slack-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-slack-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - CLAUDE_CODE_URL=${CLAUDE_CODE_URL:-http://host.docker.internal:5173}
    ports:
      - "3000:3000"
    networks:
      - claude-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Claude Code service if you want to run it in Docker as well
  # claude-code:
  #   image: anthropics/claude-code:latest
  #   container_name: claude-code
  #   restart: unless-stopped
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - claude-network
  #   volumes:
  #     - ./workspace:/workspace

networks:
  claude-network:
    driver: bridge